global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "example_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cadvisor'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor-sandbox-cadvisor:8080']
        labels:
          group: 'cadvisor'
